name: DumprX

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Firmware Link'
        required: true

env:
  LINK: ${{ github.event.inputs.link }}
  TZ: Asia/Kolkata

jobs:
  Firmware-Dump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone DumprX Repository
        run: git clone https://github.com/DumprX/DumprX.git dumprx

      - name: Cleanup Space
        uses: rokibhasansagar/slimhub_actions@main

      - name: Install Requirements
        run: |
          cd dumprx
          chmod +x setup.sh
          ./setup.sh

      - name: Configure Environment
        run: |
          cd dumprx
          git config --global user.email "sunnyteja201@gmail.com"
          git config --global user.name "JaswantTeja"
          echo "${{ secrets.GIT_TOKEN }}" > .github_token
          echo "${{ secrets.TG_TOKEN }}" > .tg_token
          echo "${{ secrets.TG_CHAT }}" > .tg_chat

      - name: Firmware Dumping
        run: |
          cd dumprx
          chmod +x dumper.sh
          ./dumper.sh "$LINK"
